import assert from 'node:assert/strict';
import {alignLinkedElements,distributeLinkedElements,selectionUnitCount} from '../src/linkedGeometry';
import {visualBox} from '../src/geometry';
import type {DesignElement,DesignPage} from '../src/types';
const el=(id:string,x:number,y:number,linkId?:string):DesignElement=>({id,name:id,type:'shape',markup:'<rect width="10" height="10"/>',bbox:{x,y,width:10,height:10},tx:0,ty:0,sx:1,sy:1,locked:false,hidden:false,linkId});
const page:DesignPage={id:'p',title:'test',width:790,height:1306,sourceWidth:790,defs:'',guides:[],elements:[el('a',10,20,'linked'),el('b',40,50,'linked'),el('c',200,20),el('d',390,20)]};
assert.equal(selectionUnitCount(page,['a','b']),1);
const aligned=alignLinkedElements(page,['a','b'],'centerX','page');
assert.equal(visualBox(aligned.elements[0]).x,375);
assert.equal(visualBox(aligned.elements[1]).x,405);
assert.equal(visualBox(aligned.elements[1]).y-visualBox(aligned.elements[0]).y,30);
assert.equal(aligned.elements[2],page.elements[2]);
const distributed=distributeLinkedElements(page,['a','b','c','d'],'x');
assert.equal(visualBox(distributed.elements[0]).x,10);
assert.equal(visualBox(distributed.elements[1]).x,40);
assert.equal(visualBox(distributed.elements[2]).x,215);
assert.equal(visualBox(distributed.elements[3]).x,390);
const single=alignLinkedElements(page,['b'],'left','page');
assert.equal(visualBox(single.elements[1]).x,0);
assert.equal(single.elements[0],page.elements[0]);
console.log('PASS linked alignment preserves internal spacing, distribution uses group bounds, direct member stays independent');
